name: Calum MacGillivray
description: This is my personal website to host information about my research and materials for training courses.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme